volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/       # Оставляем: папка backend есть
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db

  gateway:
    image: nginx:1.23       
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static       # Тот же том, что и у backend!
      - media:/media
    depends_on:
      - backend